---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    reviewers:
      - 'oap75'
      - 'olehmell'
      - "iv1310"
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'dependabot'
    pull-request-branch-name:
      separator: '/'
