/* tslint:disable */
/* eslint-disable */
// @generated
// This file was automatically generated and should not be edited.

//==============================================================
// START Enums and Input Objects
//==============================================================

export enum EventName {
  AccountFollowed = 'AccountFollowed',
  AccountUnfollowed = 'AccountUnfollowed',
  CommentCreated = 'CommentCreated',
  CommentDeleted = 'CommentDeleted',
  CommentReactionCreated = 'CommentReactionCreated',
  CommentReactionDeleted = 'CommentReactionDeleted',
  CommentReactionUpdated = 'CommentReactionUpdated',
  CommentReplyCreated = 'CommentReplyCreated',
  CommentReplyDeleted = 'CommentReplyDeleted',
  CommentReplyReactionCreated = 'CommentReplyReactionCreated',
  CommentReplyReactionDeleted = 'CommentReplyReactionDeleted',
  CommentReplyReactionUpdated = 'CommentReplyReactionUpdated',
  CommentReplyShared = 'CommentReplyShared',
  CommentReplyUpdated = 'CommentReplyUpdated',
  CommentShared = 'CommentShared',
  CommentUpdated = 'CommentUpdated',
  PostCreated = 'PostCreated',
  PostDeleted = 'PostDeleted',
  PostFollowed = 'PostFollowed',
  PostMoved = 'PostMoved',
  PostReactionCreated = 'PostReactionCreated',
  PostReactionDeleted = 'PostReactionDeleted',
  PostReactionUpdated = 'PostReactionUpdated',
  PostShared = 'PostShared',
  PostUnfollowed = 'PostUnfollowed',
  PostUpdated = 'PostUpdated',
  ProfileUpdated = 'ProfileUpdated',
  SpaceCreated = 'SpaceCreated',
  SpaceFollowed = 'SpaceFollowed',
  SpaceOwnershipTransferAccepted = 'SpaceOwnershipTransferAccepted',
  SpaceUnfollowed = 'SpaceUnfollowed',
  SpaceUpdated = 'SpaceUpdated',
}

export enum PostKind {
  Comment = 'Comment',
  RegularPost = 'RegularPost',
  SharedPost = 'SharedPost',
}

export enum ReactionKind {
  Downvote = 'Downvote',
  Upvote = 'Upvote',
}

export enum Status {
  Active = 'Active',
  Deleted = 'Deleted',
}

export interface AccountFollowersWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  followerAccount_isNull?: boolean | null
  followerAccount?: AccountWhereInput | null
  followingAccount_isNull?: boolean | null
  followingAccount?: AccountWhereInput | null
  AND?: AccountFollowersWhereInput[] | null
  OR?: AccountFollowersWhereInput[] | null
}

export interface AccountWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  profileSpace_isNull?: boolean | null
  profileSpace?: SpaceWhereInput | null
  followers_every?: AccountFollowersWhereInput | null
  followers_some?: AccountFollowersWhereInput | null
  followers_none?: AccountFollowersWhereInput | null
  followersCount_isNull?: boolean | null
  followersCount_eq?: number | null
  followersCount_not_eq?: number | null
  followersCount_gt?: number | null
  followersCount_gte?: number | null
  followersCount_lt?: number | null
  followersCount_lte?: number | null
  followersCount_in?: number[] | null
  followersCount_not_in?: number[] | null
  followingAccounts_every?: AccountFollowersWhereInput | null
  followingAccounts_some?: AccountFollowersWhereInput | null
  followingAccounts_none?: AccountFollowersWhereInput | null
  followingAccountsCount_isNull?: boolean | null
  followingAccountsCount_eq?: number | null
  followingAccountsCount_not_eq?: number | null
  followingAccountsCount_gt?: number | null
  followingAccountsCount_gte?: number | null
  followingAccountsCount_lt?: number | null
  followingAccountsCount_lte?: number | null
  followingAccountsCount_in?: number[] | null
  followingAccountsCount_not_in?: number[] | null
  posts_every?: PostWhereInput | null
  posts_some?: PostWhereInput | null
  posts_none?: PostWhereInput | null
  followingPostsCount_isNull?: boolean | null
  followingPostsCount_eq?: number | null
  followingPostsCount_not_eq?: number | null
  followingPostsCount_gt?: number | null
  followingPostsCount_gte?: number | null
  followingPostsCount_lt?: number | null
  followingPostsCount_lte?: number | null
  followingPostsCount_in?: number[] | null
  followingPostsCount_not_in?: number[] | null
  spacesCreated_every?: SpaceWhereInput | null
  spacesCreated_some?: SpaceWhereInput | null
  spacesCreated_none?: SpaceWhereInput | null
  spacesOwned_every?: SpaceWhereInput | null
  spacesOwned_some?: SpaceWhereInput | null
  spacesOwned_none?: SpaceWhereInput | null
  spacesFollowed_every?: SpaceFollowersWhereInput | null
  spacesFollowed_some?: SpaceFollowersWhereInput | null
  spacesFollowed_none?: SpaceFollowersWhereInput | null
  followingSpacesCount_isNull?: boolean | null
  followingSpacesCount_eq?: number | null
  followingSpacesCount_not_eq?: number | null
  followingSpacesCount_gt?: number | null
  followingSpacesCount_gte?: number | null
  followingSpacesCount_lt?: number | null
  followingSpacesCount_lte?: number | null
  followingSpacesCount_in?: number[] | null
  followingSpacesCount_not_in?: number[] | null
  feeds_every?: NewsFeedWhereInput | null
  feeds_some?: NewsFeedWhereInput | null
  feeds_none?: NewsFeedWhereInput | null
  notifications_every?: NotificationWhereInput | null
  notifications_some?: NotificationWhereInput | null
  notifications_none?: NotificationWhereInput | null
  activities_every?: ActivityWhereInput | null
  activities_some?: ActivityWhereInput | null
  activities_none?: ActivityWhereInput | null
  reactions_every?: ReactionWhereInput | null
  reactions_some?: ReactionWhereInput | null
  reactions_none?: ReactionWhereInput | null
  updatedAtTime_isNull?: boolean | null
  updatedAtTime_eq?: any | null
  updatedAtTime_not_eq?: any | null
  updatedAtTime_gt?: any | null
  updatedAtTime_gte?: any | null
  updatedAtTime_lt?: any | null
  updatedAtTime_lte?: any | null
  updatedAtTime_in?: any[] | null
  updatedAtTime_not_in?: any[] | null
  updatedAtBlock_isNull?: boolean | null
  updatedAtBlock_eq?: any | null
  updatedAtBlock_not_eq?: any | null
  updatedAtBlock_gt?: any | null
  updatedAtBlock_gte?: any | null
  updatedAtBlock_lt?: any | null
  updatedAtBlock_lte?: any | null
  updatedAtBlock_in?: any[] | null
  updatedAtBlock_not_in?: any[] | null
  AND?: AccountWhereInput[] | null
  OR?: AccountWhereInput[] | null
}

export interface ActivityWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  account_isNull?: boolean | null
  account?: AccountWhereInput | null
  blockNumber_isNull?: boolean | null
  blockNumber_eq?: any | null
  blockNumber_not_eq?: any | null
  blockNumber_gt?: any | null
  blockNumber_gte?: any | null
  blockNumber_lt?: any | null
  blockNumber_lte?: any | null
  blockNumber_in?: any[] | null
  blockNumber_not_in?: any[] | null
  eventIndex_isNull?: boolean | null
  eventIndex_eq?: number | null
  eventIndex_not_eq?: number | null
  eventIndex_gt?: number | null
  eventIndex_gte?: number | null
  eventIndex_lt?: number | null
  eventIndex_lte?: number | null
  eventIndex_in?: number[] | null
  eventIndex_not_in?: number[] | null
  event_isNull?: boolean | null
  event_eq?: EventName | null
  event_not_eq?: EventName | null
  event_in?: EventName[] | null
  event_not_in?: EventName[] | null
  followingAccount_isNull?: boolean | null
  followingAccount?: AccountWhereInput | null
  space_isNull?: boolean | null
  space?: SpaceWhereInput | null
  spacePrev_isNull?: boolean | null
  spacePrev?: SpaceWhereInput | null
  newOwner_isNull?: boolean | null
  newOwner?: AccountWhereInput | null
  oldOwner_isNull?: boolean | null
  oldOwner?: AccountWhereInput | null
  post_isNull?: boolean | null
  post?: PostWhereInput | null
  reaction_isNull?: boolean | null
  reaction?: ReactionWhereInput | null
  date_isNull?: boolean | null
  date_eq?: any | null
  date_not_eq?: any | null
  date_gt?: any | null
  date_gte?: any | null
  date_lt?: any | null
  date_lte?: any | null
  date_in?: any[] | null
  date_not_in?: any[] | null
  aggregated_isNull?: boolean | null
  aggregated_eq?: boolean | null
  aggregated_not_eq?: boolean | null
  aggCount_isNull?: boolean | null
  aggCount_eq?: any | null
  aggCount_not_eq?: any | null
  aggCount_gt?: any | null
  aggCount_gte?: any | null
  aggCount_lt?: any | null
  aggCount_lte?: any | null
  aggCount_in?: any[] | null
  aggCount_not_in?: any[] | null
  AND?: ActivityWhereInput[] | null
  OR?: ActivityWhereInput[] | null
}

export interface CommentFollowersWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  followerAccount_isNull?: boolean | null
  followerAccount?: AccountWhereInput | null
  followingComment_isNull?: boolean | null
  followingComment?: PostWhereInput | null
  AND?: CommentFollowersWhereInput[] | null
  OR?: CommentFollowersWhereInput[] | null
}

export interface NewsFeedWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  account_isNull?: boolean | null
  account?: AccountWhereInput | null
  activity_isNull?: boolean | null
  activity?: ActivityWhereInput | null
  AND?: NewsFeedWhereInput[] | null
  OR?: NewsFeedWhereInput[] | null
}

export interface NotificationWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  account_isNull?: boolean | null
  account?: AccountWhereInput | null
  activity_isNull?: boolean | null
  activity?: ActivityWhereInput | null
  AND?: NotificationWhereInput[] | null
  OR?: NotificationWhereInput[] | null
}

export interface PostFollowersWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  followerAccount_isNull?: boolean | null
  followerAccount?: AccountWhereInput | null
  followingPost_isNull?: boolean | null
  followingPost?: PostWhereInput | null
  AND?: PostFollowersWhereInput[] | null
  OR?: PostFollowersWhereInput[] | null
}

export interface PostWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  parentPost_isNull?: boolean | null
  parentPost?: PostWhereInput | null
  rootPost_isNull?: boolean | null
  rootPost?: PostWhereInput | null
  sharedPost_isNull?: boolean | null
  sharedPost?: PostWhereInput | null
  isComment_isNull?: boolean | null
  isComment_eq?: boolean | null
  isComment_not_eq?: boolean | null
  hidden_isNull?: boolean | null
  hidden_eq?: boolean | null
  hidden_not_eq?: boolean | null
  ownedByAccount_isNull?: boolean | null
  ownedByAccount?: AccountWhereInput | null
  createdByAccount_isNull?: boolean | null
  createdByAccount?: AccountWhereInput | null
  createdAtBlock_isNull?: boolean | null
  createdAtBlock_eq?: any | null
  createdAtBlock_not_eq?: any | null
  createdAtBlock_gt?: any | null
  createdAtBlock_gte?: any | null
  createdAtBlock_lt?: any | null
  createdAtBlock_lte?: any | null
  createdAtBlock_in?: any[] | null
  createdAtBlock_not_in?: any[] | null
  createdAtTime_isNull?: boolean | null
  createdAtTime_eq?: any | null
  createdAtTime_not_eq?: any | null
  createdAtTime_gt?: any | null
  createdAtTime_gte?: any | null
  createdAtTime_lt?: any | null
  createdAtTime_lte?: any | null
  createdAtTime_in?: any[] | null
  createdAtTime_not_in?: any[] | null
  createdOnDay_isNull?: boolean | null
  createdOnDay_eq?: any | null
  createdOnDay_not_eq?: any | null
  createdOnDay_gt?: any | null
  createdOnDay_gte?: any | null
  createdOnDay_lt?: any | null
  createdOnDay_lte?: any | null
  createdOnDay_in?: any[] | null
  createdOnDay_not_in?: any[] | null
  updatedAtTime_isNull?: boolean | null
  updatedAtTime_eq?: any | null
  updatedAtTime_not_eq?: any | null
  updatedAtTime_gt?: any | null
  updatedAtTime_gte?: any | null
  updatedAtTime_lt?: any | null
  updatedAtTime_lte?: any | null
  updatedAtTime_in?: any[] | null
  updatedAtTime_not_in?: any[] | null
  space_isNull?: boolean | null
  space?: SpaceWhereInput | null
  kind_isNull?: boolean | null
  kind_eq?: PostKind | null
  kind_not_eq?: PostKind | null
  kind_in?: PostKind[] | null
  kind_not_in?: PostKind[] | null
  postFollowers_every?: PostFollowersWhereInput | null
  postFollowers_some?: PostFollowersWhereInput | null
  postFollowers_none?: PostFollowersWhereInput | null
  commentFollowers_every?: CommentFollowersWhereInput | null
  commentFollowers_some?: CommentFollowersWhereInput | null
  commentFollowers_none?: CommentFollowersWhereInput | null
  followersCount_isNull?: boolean | null
  followersCount_eq?: number | null
  followersCount_not_eq?: number | null
  followersCount_gt?: number | null
  followersCount_gte?: number | null
  followersCount_lt?: number | null
  followersCount_lte?: number | null
  followersCount_in?: number[] | null
  followersCount_not_in?: number[] | null
  repliesCount_isNull?: boolean | null
  repliesCount_eq?: number | null
  repliesCount_not_eq?: number | null
  repliesCount_gt?: number | null
  repliesCount_gte?: number | null
  repliesCount_lt?: number | null
  repliesCount_lte?: number | null
  repliesCount_in?: number[] | null
  repliesCount_not_in?: number[] | null
  publicRepliesCount_isNull?: boolean | null
  publicRepliesCount_eq?: number | null
  publicRepliesCount_not_eq?: number | null
  publicRepliesCount_gt?: number | null
  publicRepliesCount_gte?: number | null
  publicRepliesCount_lt?: number | null
  publicRepliesCount_lte?: number | null
  publicRepliesCount_in?: number[] | null
  publicRepliesCount_not_in?: number[] | null
  hiddenRepliesCount_isNull?: boolean | null
  hiddenRepliesCount_eq?: number | null
  hiddenRepliesCount_not_eq?: number | null
  hiddenRepliesCount_gt?: number | null
  hiddenRepliesCount_gte?: number | null
  hiddenRepliesCount_lt?: number | null
  hiddenRepliesCount_lte?: number | null
  hiddenRepliesCount_in?: number[] | null
  hiddenRepliesCount_not_in?: number[] | null
  sharesCount_isNull?: boolean | null
  sharesCount_eq?: number | null
  sharesCount_not_eq?: number | null
  sharesCount_gt?: number | null
  sharesCount_gte?: number | null
  sharesCount_lt?: number | null
  sharesCount_lte?: number | null
  sharesCount_in?: number[] | null
  sharesCount_not_in?: number[] | null
  upvotesCount_isNull?: boolean | null
  upvotesCount_eq?: number | null
  upvotesCount_not_eq?: number | null
  upvotesCount_gt?: number | null
  upvotesCount_gte?: number | null
  upvotesCount_lt?: number | null
  upvotesCount_lte?: number | null
  upvotesCount_in?: number[] | null
  upvotesCount_not_in?: number[] | null
  downvotesCount_isNull?: boolean | null
  downvotesCount_eq?: number | null
  downvotesCount_not_eq?: number | null
  downvotesCount_gt?: number | null
  downvotesCount_gte?: number | null
  downvotesCount_lt?: number | null
  downvotesCount_lte?: number | null
  downvotesCount_in?: number[] | null
  downvotesCount_not_in?: number[] | null
  reactionsCount_isNull?: boolean | null
  reactionsCount_eq?: number | null
  reactionsCount_not_eq?: number | null
  reactionsCount_gt?: number | null
  reactionsCount_gte?: number | null
  reactionsCount_lt?: number | null
  reactionsCount_lte?: number | null
  reactionsCount_in?: number[] | null
  reactionsCount_not_in?: number[] | null
  reactions_every?: ReactionWhereInput | null
  reactions_some?: ReactionWhereInput | null
  reactions_none?: ReactionWhereInput | null
  title_isNull?: boolean | null
  title_eq?: string | null
  title_not_eq?: string | null
  title_gt?: string | null
  title_gte?: string | null
  title_lt?: string | null
  title_lte?: string | null
  title_in?: string[] | null
  title_not_in?: string[] | null
  title_contains?: string | null
  title_not_contains?: string | null
  title_containsInsensitive?: string | null
  title_not_containsInsensitive?: string | null
  title_startsWith?: string | null
  title_not_startsWith?: string | null
  title_endsWith?: string | null
  title_not_endsWith?: string | null
  image_isNull?: boolean | null
  image_eq?: string | null
  image_not_eq?: string | null
  image_gt?: string | null
  image_gte?: string | null
  image_lt?: string | null
  image_lte?: string | null
  image_in?: string[] | null
  image_not_in?: string[] | null
  image_contains?: string | null
  image_not_contains?: string | null
  image_containsInsensitive?: string | null
  image_not_containsInsensitive?: string | null
  image_startsWith?: string | null
  image_not_startsWith?: string | null
  image_endsWith?: string | null
  image_not_endsWith?: string | null
  link_isNull?: boolean | null
  link_eq?: string | null
  link_not_eq?: string | null
  link_gt?: string | null
  link_gte?: string | null
  link_lt?: string | null
  link_lte?: string | null
  link_in?: string[] | null
  link_not_in?: string[] | null
  link_contains?: string | null
  link_not_contains?: string | null
  link_containsInsensitive?: string | null
  link_not_containsInsensitive?: string | null
  link_startsWith?: string | null
  link_not_startsWith?: string | null
  link_endsWith?: string | null
  link_not_endsWith?: string | null
  canonical_isNull?: boolean | null
  canonical_eq?: string | null
  canonical_not_eq?: string | null
  canonical_gt?: string | null
  canonical_gte?: string | null
  canonical_lt?: string | null
  canonical_lte?: string | null
  canonical_in?: string[] | null
  canonical_not_in?: string[] | null
  canonical_contains?: string | null
  canonical_not_contains?: string | null
  canonical_containsInsensitive?: string | null
  canonical_not_containsInsensitive?: string | null
  canonical_startsWith?: string | null
  canonical_not_startsWith?: string | null
  canonical_endsWith?: string | null
  canonical_not_endsWith?: string | null
  content_isNull?: boolean | null
  content_eq?: string | null
  content_not_eq?: string | null
  content_gt?: string | null
  content_gte?: string | null
  content_lt?: string | null
  content_lte?: string | null
  content_in?: string[] | null
  content_not_in?: string[] | null
  content_contains?: string | null
  content_not_contains?: string | null
  content_containsInsensitive?: string | null
  content_not_containsInsensitive?: string | null
  content_startsWith?: string | null
  content_not_startsWith?: string | null
  content_endsWith?: string | null
  content_not_endsWith?: string | null
  slug_isNull?: boolean | null
  slug_eq?: string | null
  slug_not_eq?: string | null
  slug_gt?: string | null
  slug_gte?: string | null
  slug_lt?: string | null
  slug_lte?: string | null
  slug_in?: string[] | null
  slug_not_in?: string[] | null
  slug_contains?: string | null
  slug_not_contains?: string | null
  slug_containsInsensitive?: string | null
  slug_not_containsInsensitive?: string | null
  slug_startsWith?: string | null
  slug_not_startsWith?: string | null
  slug_endsWith?: string | null
  slug_not_endsWith?: string | null
  body_isNull?: boolean | null
  body_eq?: string | null
  body_not_eq?: string | null
  body_gt?: string | null
  body_gte?: string | null
  body_lt?: string | null
  body_lte?: string | null
  body_in?: string[] | null
  body_not_in?: string[] | null
  body_contains?: string | null
  body_not_contains?: string | null
  body_containsInsensitive?: string | null
  body_not_containsInsensitive?: string | null
  body_startsWith?: string | null
  body_not_startsWith?: string | null
  body_endsWith?: string | null
  body_not_endsWith?: string | null
  summary_isNull?: boolean | null
  summary_eq?: string | null
  summary_not_eq?: string | null
  summary_gt?: string | null
  summary_gte?: string | null
  summary_lt?: string | null
  summary_lte?: string | null
  summary_in?: string[] | null
  summary_not_in?: string[] | null
  summary_contains?: string | null
  summary_not_contains?: string | null
  summary_containsInsensitive?: string | null
  summary_not_containsInsensitive?: string | null
  summary_startsWith?: string | null
  summary_not_startsWith?: string | null
  summary_endsWith?: string | null
  summary_not_endsWith?: string | null
  isShowMore_isNull?: boolean | null
  isShowMore_eq?: boolean | null
  isShowMore_not_eq?: boolean | null
  meta_isNull?: boolean | null
  meta_eq?: string | null
  meta_not_eq?: string | null
  meta_gt?: string | null
  meta_gte?: string | null
  meta_lt?: string | null
  meta_lte?: string | null
  meta_in?: string[] | null
  meta_not_in?: string[] | null
  meta_contains?: string | null
  meta_not_contains?: string | null
  meta_containsInsensitive?: string | null
  meta_not_containsInsensitive?: string | null
  meta_startsWith?: string | null
  meta_not_startsWith?: string | null
  meta_endsWith?: string | null
  meta_not_endsWith?: string | null
  tagsOriginal_isNull?: boolean | null
  tagsOriginal_eq?: string | null
  tagsOriginal_not_eq?: string | null
  tagsOriginal_gt?: string | null
  tagsOriginal_gte?: string | null
  tagsOriginal_lt?: string | null
  tagsOriginal_lte?: string | null
  tagsOriginal_in?: string[] | null
  tagsOriginal_not_in?: string[] | null
  tagsOriginal_contains?: string | null
  tagsOriginal_not_contains?: string | null
  tagsOriginal_containsInsensitive?: string | null
  tagsOriginal_not_containsInsensitive?: string | null
  tagsOriginal_startsWith?: string | null
  tagsOriginal_not_startsWith?: string | null
  tagsOriginal_endsWith?: string | null
  tagsOriginal_not_endsWith?: string | null
  format_isNull?: boolean | null
  format_eq?: string | null
  format_not_eq?: string | null
  format_gt?: string | null
  format_gte?: string | null
  format_lt?: string | null
  format_lte?: string | null
  format_in?: string[] | null
  format_not_in?: string[] | null
  format_contains?: string | null
  format_not_contains?: string | null
  format_containsInsensitive?: string | null
  format_not_containsInsensitive?: string | null
  format_startsWith?: string | null
  format_not_startsWith?: string | null
  format_endsWith?: string | null
  format_not_endsWith?: string | null
  tweetId_isNull?: boolean | null
  tweetId_eq?: string | null
  tweetId_not_eq?: string | null
  tweetId_gt?: string | null
  tweetId_gte?: string | null
  tweetId_lt?: string | null
  tweetId_lte?: string | null
  tweetId_in?: string[] | null
  tweetId_not_in?: string[] | null
  tweetId_contains?: string | null
  tweetId_not_contains?: string | null
  tweetId_containsInsensitive?: string | null
  tweetId_not_containsInsensitive?: string | null
  tweetId_startsWith?: string | null
  tweetId_not_startsWith?: string | null
  tweetId_endsWith?: string | null
  tweetId_not_endsWith?: string | null
  tweetDetails_isNull?: boolean | null
  tweetDetails?: TweetDetailsWhereInput | null
  proposalIndex_isNull?: boolean | null
  proposalIndex_eq?: number | null
  proposalIndex_not_eq?: number | null
  proposalIndex_gt?: number | null
  proposalIndex_gte?: number | null
  proposalIndex_lt?: number | null
  proposalIndex_lte?: number | null
  proposalIndex_in?: number[] | null
  proposalIndex_not_in?: number[] | null
  AND?: PostWhereInput[] | null
  OR?: PostWhereInput[] | null
}

export interface ReactionWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  post_isNull?: boolean | null
  post?: PostWhereInput | null
  account_isNull?: boolean | null
  account?: AccountWhereInput | null
  kind_isNull?: boolean | null
  kind_eq?: ReactionKind | null
  kind_not_eq?: ReactionKind | null
  kind_in?: ReactionKind[] | null
  kind_not_in?: ReactionKind[] | null
  status_isNull?: boolean | null
  status_eq?: Status | null
  status_not_eq?: Status | null
  status_in?: Status[] | null
  status_not_in?: Status[] | null
  createdAtBlock_isNull?: boolean | null
  createdAtBlock_eq?: any | null
  createdAtBlock_not_eq?: any | null
  createdAtBlock_gt?: any | null
  createdAtBlock_gte?: any | null
  createdAtBlock_lt?: any | null
  createdAtBlock_lte?: any | null
  createdAtBlock_in?: any[] | null
  createdAtBlock_not_in?: any[] | null
  createdAtTime_isNull?: boolean | null
  createdAtTime_eq?: any | null
  createdAtTime_not_eq?: any | null
  createdAtTime_gt?: any | null
  createdAtTime_gte?: any | null
  createdAtTime_lt?: any | null
  createdAtTime_lte?: any | null
  createdAtTime_in?: any[] | null
  createdAtTime_not_in?: any[] | null
  updatedAtBlock_isNull?: boolean | null
  updatedAtBlock_eq?: any | null
  updatedAtBlock_not_eq?: any | null
  updatedAtBlock_gt?: any | null
  updatedAtBlock_gte?: any | null
  updatedAtBlock_lt?: any | null
  updatedAtBlock_lte?: any | null
  updatedAtBlock_in?: any[] | null
  updatedAtBlock_not_in?: any[] | null
  updatedAtTime_isNull?: boolean | null
  updatedAtTime_eq?: any | null
  updatedAtTime_not_eq?: any | null
  updatedAtTime_gt?: any | null
  updatedAtTime_gte?: any | null
  updatedAtTime_lt?: any | null
  updatedAtTime_lte?: any | null
  updatedAtTime_in?: any[] | null
  updatedAtTime_not_in?: any[] | null
  AND?: ReactionWhereInput[] | null
  OR?: ReactionWhereInput[] | null
}

export interface SpaceFollowersWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  followerAccount_isNull?: boolean | null
  followerAccount?: AccountWhereInput | null
  followingSpace_isNull?: boolean | null
  followingSpace?: SpaceWhereInput | null
  AND?: SpaceFollowersWhereInput[] | null
  OR?: SpaceFollowersWhereInput[] | null
}

export interface SpacePermissionsWhereInput {
  manageRoles_isNull?: boolean | null
  manageRoles_eq?: boolean | null
  manageRoles_not_eq?: boolean | null
  representSpaceInternally_isNull?: boolean | null
  representSpaceInternally_eq?: boolean | null
  representSpaceInternally_not_eq?: boolean | null
  representSpaceExternally_isNull?: boolean | null
  representSpaceExternally_eq?: boolean | null
  representSpaceExternally_not_eq?: boolean | null
  updateSpace_isNull?: boolean | null
  updateSpace_eq?: boolean | null
  updateSpace_not_eq?: boolean | null
  createSubspaces_isNull?: boolean | null
  createSubspaces_eq?: boolean | null
  createSubspaces_not_eq?: boolean | null
  updateOwnSubspaces_isNull?: boolean | null
  updateOwnSubspaces_eq?: boolean | null
  updateOwnSubspaces_not_eq?: boolean | null
  deleteOwnSubspaces_isNull?: boolean | null
  deleteOwnSubspaces_eq?: boolean | null
  deleteOwnSubspaces_not_eq?: boolean | null
  hideOwnSubspaces_isNull?: boolean | null
  hideOwnSubspaces_eq?: boolean | null
  hideOwnSubspaces_not_eq?: boolean | null
  updateAnySubspace_isNull?: boolean | null
  updateAnySubspace_eq?: boolean | null
  updateAnySubspace_not_eq?: boolean | null
  deleteAnySubspace_isNull?: boolean | null
  deleteAnySubspace_eq?: boolean | null
  deleteAnySubspace_not_eq?: boolean | null
  hideAnySubspace_isNull?: boolean | null
  hideAnySubspace_eq?: boolean | null
  hideAnySubspace_not_eq?: boolean | null
  createPosts_isNull?: boolean | null
  createPosts_eq?: boolean | null
  createPosts_not_eq?: boolean | null
  updateOwnPosts_isNull?: boolean | null
  updateOwnPosts_eq?: boolean | null
  updateOwnPosts_not_eq?: boolean | null
  deleteOwnPosts_isNull?: boolean | null
  deleteOwnPosts_eq?: boolean | null
  deleteOwnPosts_not_eq?: boolean | null
  hideOwnPosts_isNull?: boolean | null
  hideOwnPosts_eq?: boolean | null
  hideOwnPosts_not_eq?: boolean | null
  updateAnyPost_isNull?: boolean | null
  updateAnyPost_eq?: boolean | null
  updateAnyPost_not_eq?: boolean | null
  deleteAnyPost_isNull?: boolean | null
  deleteAnyPost_eq?: boolean | null
  deleteAnyPost_not_eq?: boolean | null
  hideAnyPost_isNull?: boolean | null
  hideAnyPost_eq?: boolean | null
  hideAnyPost_not_eq?: boolean | null
  createComments_isNull?: boolean | null
  createComments_eq?: boolean | null
  createComments_not_eq?: boolean | null
  updateOwnComments_isNull?: boolean | null
  updateOwnComments_eq?: boolean | null
  updateOwnComments_not_eq?: boolean | null
  deleteOwnComments_isNull?: boolean | null
  deleteOwnComments_eq?: boolean | null
  deleteOwnComments_not_eq?: boolean | null
  hideOwnComments_isNull?: boolean | null
  hideOwnComments_eq?: boolean | null
  hideOwnComments_not_eq?: boolean | null
  hideAnyComment_isNull?: boolean | null
  hideAnyComment_eq?: boolean | null
  hideAnyComment_not_eq?: boolean | null
  upvote_isNull?: boolean | null
  upvote_eq?: boolean | null
  upvote_not_eq?: boolean | null
  downvote_isNull?: boolean | null
  downvote_eq?: boolean | null
  downvote_not_eq?: boolean | null
  share_isNull?: boolean | null
  share_eq?: boolean | null
  share_not_eq?: boolean | null
  overrideSubspacePermissions_isNull?: boolean | null
  overrideSubspacePermissions_eq?: boolean | null
  overrideSubspacePermissions_not_eq?: boolean | null
  overridePostPermissions_isNull?: boolean | null
  overridePostPermissions_eq?: boolean | null
  overridePostPermissions_not_eq?: boolean | null
  suggestEntityStatus_isNull?: boolean | null
  suggestEntityStatus_eq?: boolean | null
  suggestEntityStatus_not_eq?: boolean | null
  updateEntityStatus_isNull?: boolean | null
  updateEntityStatus_eq?: boolean | null
  updateEntityStatus_not_eq?: boolean | null
  updateSpaceSettings_isNull?: boolean | null
  updateSpaceSettings_eq?: boolean | null
  updateSpaceSettings_not_eq?: boolean | null
}

export interface SpaceWhereInput {
  id_isNull?: boolean | null
  id_eq?: string | null
  id_not_eq?: string | null
  id_gt?: string | null
  id_gte?: string | null
  id_lt?: string | null
  id_lte?: string | null
  id_in?: string[] | null
  id_not_in?: string[] | null
  id_contains?: string | null
  id_not_contains?: string | null
  id_containsInsensitive?: string | null
  id_not_containsInsensitive?: string | null
  id_startsWith?: string | null
  id_not_startsWith?: string | null
  id_endsWith?: string | null
  id_not_endsWith?: string | null
  createdByAccount_isNull?: boolean | null
  createdByAccount?: AccountWhereInput | null
  ownedByAccount_isNull?: boolean | null
  ownedByAccount?: AccountWhereInput | null
  profileSpace_isNull?: boolean | null
  profileSpace?: AccountWhereInput | null
  createdAtBlock_isNull?: boolean | null
  createdAtBlock_eq?: any | null
  createdAtBlock_not_eq?: any | null
  createdAtBlock_gt?: any | null
  createdAtBlock_gte?: any | null
  createdAtBlock_lt?: any | null
  createdAtBlock_lte?: any | null
  createdAtBlock_in?: any[] | null
  createdAtBlock_not_in?: any[] | null
  createdAtTime_isNull?: boolean | null
  createdAtTime_eq?: any | null
  createdAtTime_not_eq?: any | null
  createdAtTime_gt?: any | null
  createdAtTime_gte?: any | null
  createdAtTime_lt?: any | null
  createdAtTime_lte?: any | null
  createdAtTime_in?: any[] | null
  createdAtTime_not_in?: any[] | null
  createdOnDay_isNull?: boolean | null
  createdOnDay_eq?: any | null
  createdOnDay_not_eq?: any | null
  createdOnDay_gt?: any | null
  createdOnDay_gte?: any | null
  createdOnDay_lt?: any | null
  createdOnDay_lte?: any | null
  createdOnDay_in?: any[] | null
  createdOnDay_not_in?: any[] | null
  updatedAtTime_isNull?: boolean | null
  updatedAtTime_eq?: any | null
  updatedAtTime_not_eq?: any | null
  updatedAtTime_gt?: any | null
  updatedAtTime_gte?: any | null
  updatedAtTime_lt?: any | null
  updatedAtTime_lte?: any | null
  updatedAtTime_in?: any[] | null
  updatedAtTime_not_in?: any[] | null
  updatedAtBlock_isNull?: boolean | null
  updatedAtBlock_eq?: any | null
  updatedAtBlock_not_eq?: any | null
  updatedAtBlock_gt?: any | null
  updatedAtBlock_gte?: any | null
  updatedAtBlock_lt?: any | null
  updatedAtBlock_lte?: any | null
  updatedAtBlock_in?: any[] | null
  updatedAtBlock_not_in?: any[] | null
  posts_every?: PostWhereInput | null
  posts_some?: PostWhereInput | null
  posts_none?: PostWhereInput | null
  postsCount_isNull?: boolean | null
  postsCount_eq?: number | null
  postsCount_not_eq?: number | null
  postsCount_gt?: number | null
  postsCount_gte?: number | null
  postsCount_lt?: number | null
  postsCount_lte?: number | null
  postsCount_in?: number[] | null
  postsCount_not_in?: number[] | null
  publicPostsCount_isNull?: boolean | null
  publicPostsCount_eq?: number | null
  publicPostsCount_not_eq?: number | null
  publicPostsCount_gt?: number | null
  publicPostsCount_gte?: number | null
  publicPostsCount_lt?: number | null
  publicPostsCount_lte?: number | null
  publicPostsCount_in?: number[] | null
  publicPostsCount_not_in?: number[] | null
  hiddenPostsCount_isNull?: boolean | null
  hiddenPostsCount_eq?: number | null
  hiddenPostsCount_not_eq?: number | null
  hiddenPostsCount_gt?: number | null
  hiddenPostsCount_gte?: number | null
  hiddenPostsCount_lt?: number | null
  hiddenPostsCount_lte?: number | null
  hiddenPostsCount_in?: number[] | null
  hiddenPostsCount_not_in?: number[] | null
  hidden_isNull?: boolean | null
  hidden_eq?: boolean | null
  hidden_not_eq?: boolean | null
  content_isNull?: boolean | null
  content_eq?: string | null
  content_not_eq?: string | null
  content_gt?: string | null
  content_gte?: string | null
  content_lt?: string | null
  content_lte?: string | null
  content_in?: string[] | null
  content_not_in?: string[] | null
  content_contains?: string | null
  content_not_contains?: string | null
  content_containsInsensitive?: string | null
  content_not_containsInsensitive?: string | null
  content_startsWith?: string | null
  content_not_startsWith?: string | null
  content_endsWith?: string | null
  content_not_endsWith?: string | null
  name_isNull?: boolean | null
  name_eq?: string | null
  name_not_eq?: string | null
  name_gt?: string | null
  name_gte?: string | null
  name_lt?: string | null
  name_lte?: string | null
  name_in?: string[] | null
  name_not_in?: string[] | null
  name_contains?: string | null
  name_not_contains?: string | null
  name_containsInsensitive?: string | null
  name_not_containsInsensitive?: string | null
  name_startsWith?: string | null
  name_not_startsWith?: string | null
  name_endsWith?: string | null
  name_not_endsWith?: string | null
  image_isNull?: boolean | null
  image_eq?: string | null
  image_not_eq?: string | null
  image_gt?: string | null
  image_gte?: string | null
  image_lt?: string | null
  image_lte?: string | null
  image_in?: string[] | null
  image_not_in?: string[] | null
  image_contains?: string | null
  image_not_contains?: string | null
  image_containsInsensitive?: string | null
  image_not_containsInsensitive?: string | null
  image_startsWith?: string | null
  image_not_startsWith?: string | null
  image_endsWith?: string | null
  image_not_endsWith?: string | null
  about_isNull?: boolean | null
  about_eq?: string | null
  about_not_eq?: string | null
  about_gt?: string | null
  about_gte?: string | null
  about_lt?: string | null
  about_lte?: string | null
  about_in?: string[] | null
  about_not_in?: string[] | null
  about_contains?: string | null
  about_not_contains?: string | null
  about_containsInsensitive?: string | null
  about_not_containsInsensitive?: string | null
  about_startsWith?: string | null
  about_not_startsWith?: string | null
  about_endsWith?: string | null
  about_not_endsWith?: string | null
  summary_isNull?: boolean | null
  summary_eq?: string | null
  summary_not_eq?: string | null
  summary_gt?: string | null
  summary_gte?: string | null
  summary_lt?: string | null
  summary_lte?: string | null
  summary_in?: string[] | null
  summary_not_in?: string[] | null
  summary_contains?: string | null
  summary_not_contains?: string | null
  summary_containsInsensitive?: string | null
  summary_not_containsInsensitive?: string | null
  summary_startsWith?: string | null
  summary_not_startsWith?: string | null
  summary_endsWith?: string | null
  summary_not_endsWith?: string | null
  isShowMore_isNull?: boolean | null
  isShowMore_eq?: boolean | null
  isShowMore_not_eq?: boolean | null
  email_isNull?: boolean | null
  email_eq?: string | null
  email_not_eq?: string | null
  email_gt?: string | null
  email_gte?: string | null
  email_lt?: string | null
  email_lte?: string | null
  email_in?: string[] | null
  email_not_in?: string[] | null
  email_contains?: string | null
  email_not_contains?: string | null
  email_containsInsensitive?: string | null
  email_not_containsInsensitive?: string | null
  email_startsWith?: string | null
  email_not_startsWith?: string | null
  email_endsWith?: string | null
  email_not_endsWith?: string | null
  tagsOriginal_isNull?: boolean | null
  tagsOriginal_eq?: string | null
  tagsOriginal_not_eq?: string | null
  tagsOriginal_gt?: string | null
  tagsOriginal_gte?: string | null
  tagsOriginal_lt?: string | null
  tagsOriginal_lte?: string | null
  tagsOriginal_in?: string[] | null
  tagsOriginal_not_in?: string[] | null
  tagsOriginal_contains?: string | null
  tagsOriginal_not_contains?: string | null
  tagsOriginal_containsInsensitive?: string | null
  tagsOriginal_not_containsInsensitive?: string | null
  tagsOriginal_startsWith?: string | null
  tagsOriginal_not_startsWith?: string | null
  tagsOriginal_endsWith?: string | null
  tagsOriginal_not_endsWith?: string | null
  linksOriginal_isNull?: boolean | null
  linksOriginal_eq?: string | null
  linksOriginal_not_eq?: string | null
  linksOriginal_gt?: string | null
  linksOriginal_gte?: string | null
  linksOriginal_lt?: string | null
  linksOriginal_lte?: string | null
  linksOriginal_in?: string[] | null
  linksOriginal_not_in?: string[] | null
  linksOriginal_contains?: string | null
  linksOriginal_not_contains?: string | null
  linksOriginal_containsInsensitive?: string | null
  linksOriginal_not_containsInsensitive?: string | null
  linksOriginal_startsWith?: string | null
  linksOriginal_not_startsWith?: string | null
  linksOriginal_endsWith?: string | null
  linksOriginal_not_endsWith?: string | null
  interestsOriginal_isNull?: boolean | null
  interestsOriginal_eq?: string | null
  interestsOriginal_not_eq?: string | null
  interestsOriginal_gt?: string | null
  interestsOriginal_gte?: string | null
  interestsOriginal_lt?: string | null
  interestsOriginal_lte?: string | null
  interestsOriginal_in?: string[] | null
  interestsOriginal_not_in?: string[] | null
  interestsOriginal_contains?: string | null
  interestsOriginal_not_contains?: string | null
  interestsOriginal_containsInsensitive?: string | null
  interestsOriginal_not_containsInsensitive?: string | null
  interestsOriginal_startsWith?: string | null
  interestsOriginal_not_startsWith?: string | null
  interestsOriginal_endsWith?: string | null
  interestsOriginal_not_endsWith?: string | null
  format_isNull?: boolean | null
  format_eq?: string | null
  format_not_eq?: string | null
  format_gt?: string | null
  format_gte?: string | null
  format_lt?: string | null
  format_lte?: string | null
  format_in?: string[] | null
  format_not_in?: string[] | null
  format_contains?: string | null
  format_not_contains?: string | null
  format_containsInsensitive?: string | null
  format_not_containsInsensitive?: string | null
  format_startsWith?: string | null
  format_not_startsWith?: string | null
  format_endsWith?: string | null
  format_not_endsWith?: string | null
  handle_isNull?: boolean | null
  handle_eq?: string | null
  handle_not_eq?: string | null
  handle_gt?: string | null
  handle_gte?: string | null
  handle_lt?: string | null
  handle_lte?: string | null
  handle_in?: string[] | null
  handle_not_in?: string[] | null
  handle_contains?: string | null
  handle_not_contains?: string | null
  handle_containsInsensitive?: string | null
  handle_not_containsInsensitive?: string | null
  handle_startsWith?: string | null
  handle_not_startsWith?: string | null
  handle_endsWith?: string | null
  handle_not_endsWith?: string | null
  canFollowerCreatePosts_isNull?: boolean | null
  canFollowerCreatePosts_eq?: boolean | null
  canFollowerCreatePosts_not_eq?: boolean | null
  canEveryoneCreatePosts_isNull?: boolean | null
  canEveryoneCreatePosts_eq?: boolean | null
  canEveryoneCreatePosts_not_eq?: boolean | null
  nonePermissions_isNull?: boolean | null
  nonePermissions?: SpacePermissionsWhereInput | null
  everyonePermissions_isNull?: boolean | null
  everyonePermissions?: SpacePermissionsWhereInput | null
  followerPermissions_isNull?: boolean | null
  followerPermissions?: SpacePermissionsWhereInput | null
  spaceOwnerPermissions_isNull?: boolean | null
  spaceOwnerPermissions?: SpacePermissionsWhereInput | null
  followersCount_isNull?: boolean | null
  followersCount_eq?: number | null
  followersCount_not_eq?: number | null
  followersCount_gt?: number | null
  followersCount_gte?: number | null
  followersCount_lt?: number | null
  followersCount_lte?: number | null
  followersCount_in?: number[] | null
  followersCount_not_in?: number[] | null
  followers_every?: SpaceFollowersWhereInput | null
  followers_some?: SpaceFollowersWhereInput | null
  followers_none?: SpaceFollowersWhereInput | null
  AND?: SpaceWhereInput[] | null
  OR?: SpaceWhereInput[] | null
}

export interface TweetDetailsWhereInput {
  createdAt_isNull?: boolean | null
  createdAt_eq?: string | null
  createdAt_not_eq?: string | null
  createdAt_gt?: string | null
  createdAt_gte?: string | null
  createdAt_lt?: string | null
  createdAt_lte?: string | null
  createdAt_in?: string[] | null
  createdAt_not_in?: string[] | null
  createdAt_contains?: string | null
  createdAt_not_contains?: string | null
  createdAt_containsInsensitive?: string | null
  createdAt_not_containsInsensitive?: string | null
  createdAt_startsWith?: string | null
  createdAt_not_startsWith?: string | null
  createdAt_endsWith?: string | null
  createdAt_not_endsWith?: string | null
  username_isNull?: boolean | null
  username_eq?: string | null
  username_not_eq?: string | null
  username_gt?: string | null
  username_gte?: string | null
  username_lt?: string | null
  username_lte?: string | null
  username_in?: string[] | null
  username_not_in?: string[] | null
  username_contains?: string | null
  username_not_contains?: string | null
  username_containsInsensitive?: string | null
  username_not_containsInsensitive?: string | null
  username_startsWith?: string | null
  username_not_startsWith?: string | null
  username_endsWith?: string | null
  username_not_endsWith?: string | null
  authorId_isNull?: boolean | null
  authorId_eq?: string | null
  authorId_not_eq?: string | null
  authorId_gt?: string | null
  authorId_gte?: string | null
  authorId_lt?: string | null
  authorId_lte?: string | null
  authorId_in?: string[] | null
  authorId_not_in?: string[] | null
  authorId_contains?: string | null
  authorId_not_contains?: string | null
  authorId_containsInsensitive?: string | null
  authorId_not_containsInsensitive?: string | null
  authorId_startsWith?: string | null
  authorId_not_startsWith?: string | null
  authorId_endsWith?: string | null
  authorId_not_endsWith?: string | null
  editHistoryTweetIds_isNull?: boolean | null
  editHistoryTweetIds_containsAll?: (string | null)[] | null
  editHistoryTweetIds_containsAny?: (string | null)[] | null
  editHistoryTweetIds_containsNone?: (string | null)[] | null
  conversationId_isNull?: boolean | null
  conversationId_eq?: string | null
  conversationId_not_eq?: string | null
  conversationId_gt?: string | null
  conversationId_gte?: string | null
  conversationId_lt?: string | null
  conversationId_lte?: string | null
  conversationId_in?: string[] | null
  conversationId_not_in?: string[] | null
  conversationId_contains?: string | null
  conversationId_not_contains?: string | null
  conversationId_containsInsensitive?: string | null
  conversationId_not_containsInsensitive?: string | null
  conversationId_startsWith?: string | null
  conversationId_not_startsWith?: string | null
  conversationId_endsWith?: string | null
  conversationId_not_endsWith?: string | null
  inReplyToUserId_isNull?: boolean | null
  inReplyToUserId_eq?: string | null
  inReplyToUserId_not_eq?: string | null
  inReplyToUserId_gt?: string | null
  inReplyToUserId_gte?: string | null
  inReplyToUserId_lt?: string | null
  inReplyToUserId_lte?: string | null
  inReplyToUserId_in?: string[] | null
  inReplyToUserId_not_in?: string[] | null
  inReplyToUserId_contains?: string | null
  inReplyToUserId_not_contains?: string | null
  inReplyToUserId_containsInsensitive?: string | null
  inReplyToUserId_not_containsInsensitive?: string | null
  inReplyToUserId_startsWith?: string | null
  inReplyToUserId_not_startsWith?: string | null
  inReplyToUserId_endsWith?: string | null
  inReplyToUserId_not_endsWith?: string | null
  referencedTweets_isNull?: boolean | null
  attachments_isNull?: boolean | null
  lang_isNull?: boolean | null
  lang_eq?: string | null
  lang_not_eq?: string | null
  lang_gt?: string | null
  lang_gte?: string | null
  lang_lt?: string | null
  lang_lte?: string | null
  lang_in?: string[] | null
  lang_not_in?: string[] | null
  lang_contains?: string | null
  lang_not_contains?: string | null
  lang_containsInsensitive?: string | null
  lang_not_containsInsensitive?: string | null
  lang_startsWith?: string | null
  lang_not_startsWith?: string | null
  lang_endsWith?: string | null
  lang_not_endsWith?: string | null
}

//==============================================================
// END Enums and Input Objects
//==============================================================
